services:
  mai-db-postgres:
    container_name: mai-db-postgres
    image: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 3
    hostname: mai-db-postgres
    ports:
      - "5555:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ../lab_2/00000-startup-scripts:/docker-entrypoint-initdb.d:ro
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

volumes:
  postgres-data: